name: Main Auto Tag
on:
  push:
    branches:
      - main

jobs:
  tagged-release:
    name: "Main Auto Tag"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - uses: Paxx-RnD/incremental-tag@latest
        with:
          flag_branch: true
          message: Bump version
          prev_tag: 'v'
          update_odoo_module_version: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
